### PR TITLE
Spring cleaning

### PR DESCRIPTION
**Pull request by ghost**
Told ya.

### CODE REVIEW

**Comment by thepieterdc** [comment]
List comprehension @ for loops(when printing menu) please =)

**Comment by ghost** [comment]
That's less pythonic (since we're not actually creating a list), not more readable, and it creates a list full of `None`s in memory. But here you go. (commit above ↑)

**Comment by thepieterdc** [comment]
Reverted: Image

@M1dgard

**Comment by ghost** [comment]
Those last two are your own fault, with your list comprehensions :p

**Comment by thepieterdc** [comment]
Was 100% before merge ;)
Op 13-apr.-2016 09:12 schreef "Midgard" notifications@github.com:

**Comment by ghost** [comment]
I don't believe it for a second.

**Pull request merged**
